approvedGitRepositories:
  - '**'

compressionLevel: mixed

enableGlobalCache: false

enableInlineBuilds: true

enableInlineHunks: true

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0
